spring:
  batch:
    jdbc:
      initialize-schema: always
  main:
    web-application-type: none
  application:
    name: demo1
  config:
    import: optional:file:.env[.properties]
  ai:
    openai:
      api-key: ${OPENROUTER_KEY}
      base-url: https://openrouter.ai/api
      embedding:
        api-key: ${OPENAI_GPT_KEY}
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: ${OPENROUTER_MODEL}
    vectorstore:
      chroma:
        client:
          host: ${CHROMA_URL}
          port: ${CHROMA_PORT}
        collection-name: stock_news_vectors
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_ID}
    password: ${MYSQL_KEY}
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        default_batch_fetch_size: 100
        show_sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: update

