spring:
  main:
    web-application-type: none
  application:
    name: demo1
  config:
    import: classpath:config.properties
  ai:
    openai:
      api-key: ${GPT_KEY}
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test123;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=true;MODE=MySQL;
    username: sa
    password:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        default_batch_fetch_size: 100
        show_sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      ddl-auto: create-drop

